Add head main
ichiro-its/atama pull request #6
Opened 2021-06-12 22:58 UTC by Nathan24zz

Close #5.

2021-06-13 17:22 UTC, segara2410 requested changes

2021-06-13 17:22 UTC, segara2410 commented on include/atama/head.hpp
> +    std::shared_ptr<Head> head, std::shared_ptr<CameraMeasurement> camera,
Remove head from parameters.

2021-06-13 17:42 UTC, segara2410 approved these changes
LGTM

2021-06-14 04:56 UTC, maroqijalil approved these changes
LGTm

2021-06-14 04:57 UTC, merged